export interface BoardMember {
  id: string;
  name: string;
  role: string;
  pmaClass: string;
  image: string;
  highlights: string[];
  group: "officer" | "committee" | "trustee";
}

// Source of truth for credentials: references/board_member_details.md
export const boardMembers: BoardMember[] = [
  // Officers
  {
    id: "leuterio",
    name: "Leo Angelo D. Leuterio",
    role: "Chairman",
    pmaClass: "PMA '88",
    image: "/board/leuterio.png",
    highlights: [
      "PhD units in PASA, Bicol University",
      "Masters in Management (Industrial Relations), UP",
      "Diploma in Results Based Management, AIM",
      "Vice Chairman, Holy Child College of Davao",
    ],
    group: "officer",
  },
  {
    id: "lalisan",
    name: "Jose C. Lalisan Jr.",
    role: "Vice Chairman & Corporate Auditor",
    pmaClass: "PMA '71",
    image: "/board/lalisan.png",
    highlights: [
      "Director, Directorate for Personnel and Record Management, PNP",
      "Master in National Security Administration, NDCP",
      "Executive Security Consultant, EEI",
      "Past Director, Rotary Club of Davao",
      "Charter Member, Rotary Club of San Juan del Monte",
    ],
    group: "officer",
  },
  {
    id: "bacarro",
    name: "Bartolome Vicente O. Bacarro",
    role: "President & Chairman, Executive Committee",
    pmaClass: "PMA '88",
    image: "/board/bacarro.jpg",
    highlights: [
      "Chief of Staff, AFP (2022)",
      "Medal of Valor Awardee",
      "Commander, Southern Luzon Command",
      "Commander, 2nd Infantry Division",
      "Commandant of Cadets, PMA",
      "Commander, 502nd Infantry Brigade",
    ],
    group: "officer",
  },
  {
    id: "esguerra",
    name: "Salvador Q. Esguerra",
    role: "Vice President & Chairman, Nomination & Election Committee",
    pmaClass: "PMA '74",
    image: "/board/esguerra.png",
    highlights: [
      "BS Electrical Engineering, UP Diliman",
      "Master in Management",
      "Commander, AFP CEIS",
      "Executive Director, AGFO",
      "Trustee, AGFO Foundation, Inc.",
      "Deputy Administrator, PVAO",
      "Vice President for Operations, VFP",
      "Cavaliers Award, Naval Operation, PMAAAI 1974",
    ],
    group: "officer",
  },
  // Committee Officers
  {
    id: "meneses",
    name: "Gil C. Meneses",
    role: "Corporate Secretary",
    pmaClass: "PMA '80",
    image: "/board/meneses.png",
    highlights: [
      "Magna Cum Laude, Graduate #2",
      "PhD, Peace and Security Administration",
      "Masters, Public Safety Administration (Silver Medal)",
      "Bachelor of Laws (LLB), Cum Laude",
      "Director, Civil Security Group (CSG), PNP",
      "Technical Consultant, PMS, OP (2017–2022)",
      "Member, Rotary Club of Loyola Heights, QC",
      "Member, Philippine Bar (1994)",
    ],
    group: "committee",
  },
  {
    id: "aquino",
    name: "Rolando M. Aquino",
    role: "Treasurer & Chairman, Finance Committee",
    pmaClass: "PMA '83",
    image: "/board/aquino.png",
    highlights: [
      "Master in Defense Studies, University of Canberra, Australia",
      "Wing Commander, 205th TW & 410th MW",
      "Independent Trustee, AFPMBAI (2015–2016)",
      "Member, BOD, Air Cavalier Credit Coop (2015–2021)",
      "Presidential Lingkod Bayan Award, CSC (2014)",
      "The Outstanding Philippine Soldier (2006)",
      "Cavalier Award, Air Force Operations (1994)",
    ],
    group: "committee",
  },
  {
    id: "ibay",
    name: "Rufino G. Ibay Jr.",
    role: "Chairman, Awards Committee",
    pmaClass: "PMA '67",
    image: "/board/ibay.png",
    highlights: [
      "Academic Board Star",
      "Masters Degree in Economics, UP School of Economics",
      "Director for Comptrollership, PNP",
      "President & CEO, AFPSLAI (2003–2006)",
      "Acting Chairperson, John Hay Management Corporation",
      "Member, Rotary Club of Pasay MIA",
      "MA in Economics; PhD in Peace and Security, Bicol University",
    ],
    group: "committee",
  },
  {
    id: "mariano",
    name: "Manuel B. Mariano",
    role: "Chairman, Bylaws Amendment Committee",
    pmaClass: "PMA '62",
    image: "/board/mariano.png",
    highlights: [
      "Masters in Management, AIM",
      "Masters in Business Economics, UA&P",
      "Commander, AFP LOGCOM",
      "Chairman and CEO, Videogram Regulatory Board",
      "Member, BOT, TG PMA HOP Foundation",
      "Distinguished Conduct Star",
      "Presidential Lingkod Bayan Award",
      "President, Rotary Club of Greenmeadows",
      "First AFP Senior Officer Graduate, National Defense University, Washington DC, USA",
    ],
    group: "committee",
  },
  {
    id: "anselmo",
    name: "Anselmo S. Avenido Jr.",
    role: "Chairman, Policy Formulation Committee",
    pmaClass: "PMA '67",
    image: "/board/anselmo.png",
    highlights: [
      "Graduate #1, Summa Cum Laude & Academic Star Awardee",
      "P/Lieutenant General, PNP (Ret.)",
      "P/Deputy Director General, PNP",
      "MPA, UP; MBGA, ADMU; MMAS, USACGSC",
      "Director General, PDEA",
      "Chairman, Dangerous Drug Board",
      "Undersecretary, DILG",
      "Chairman, PMAAAI (2015–2016)",
      "President, PETFI",
      "Chairman & President, PMAFI",
    ],
    group: "committee",
  },
  {
    id: "doplayna",
    name: "Demosthenes C. Doplayna",
    role: "Chairman, Membership Committee",
    pmaClass: "PMA '82",
    image: "/board/doplayna.png",
    highlights: [
      "BS PMA 1982 with Academic Board Star",
      "Master in Business Management, AIM (1993)",
      "Head, Investment Assistance Department, AFPRSBS (1994–1996)",
      "President, PMA Development Foundation Inc. (2013–2018)",
      "Managing Director, Facilities Managers Inc.",
      "Chairman & President, Facility Servisys Inc.",
      "Cavaliers Award, PMAAAI (2023)",
    ],
    group: "committee",
  },
  {
    id: "manalastas",
    name: "Florentino P. Manalastas Jr.",
    role: "Chairman, Project Evaluation Committee",
    pmaClass: "PMA '83",
    image: "/board/manalastas.png",
    highlights: [
      "Master in Business Administration, UP (1988)",
      "Juris Doctor, St. Louis University, BC (1994)",
      "Executive Doctorate in Education Leadership (lacking dissertation), DAP",
      "Dean, Corps of Professors, AFP",
      "OIC-Executive Director, ATC-PMC, OP",
      "Corporate Secretary, AFPSLAI",
      "Dangal na Lipi Awardee (Bulacan)",
    ],
    group: "committee",
  },
  {
    id: "corpuz",
    name: "Allan O. Corpuz",
    role: "Chairman, Ways & Means Committee",
    pmaClass: "PMA '91",
    image: "/board/corpuz.png",
    highlights: [
      "MBA (Top Executive Program), PLM",
      "MPM major in Security & Development, DAP",
      "PhD in Public Administration, GPTU",
      "MNSA, NDCP",
      "Commander, Coast Guard District SEM / Coast Guard Mindanao Area Command",
      "Secretary General & Corporate Secretary, TFOE-PE, Inc.",
      "DPDGL/PGLI/PM, GLF&AMP",
      "Past High Sheriff, Balisong Shrine Club",
      "Most Outstanding Worshipful Master, MD NCR-C (MY 2022–23)",
    ],
    group: "committee",
  },
  // Trustees
  {
    id: "lapus",
    name: "Jose C. Lapus",
    role: "Trustee",
    pmaClass: "PMA '65",
    image: "/board/lapus.png",
    highlights: [
      "Cavalier Awardee, PMAAAI (2017)",
      "Commanding General, Visayas Command",
      "MBA, UP",
      "MPA, MLQU",
      "Board of Director, PHIVIDEC",
      "President, Mindanao Steel Corporation",
    ],
    group: "trustee",
  },
  {
    id: "aguilar",
    name: "Restituto L. Aguilar",
    role: "Trustee",
    pmaClass: "PMA '78",
    image: "/board/aguilar.png",
    highlights: [
      "Deputy Administrator, Philippine Veterans Affairs Office (2022–present)",
      "Executive Director, National Historical Commission of the Philippines (2020–2021)",
      "Editor-in-Chief, Cavalier Magazine, PMAAAI (2002–2012)",
      "Editor, Cavalier Handbook (2012 & 2015 Editions)",
      "Author, Academy Register (2016)",
      "Treasurer, PMA Foundation, Inc. (2020–present)",
      "Cavalier Award, PMAAAI (2011)",
    ],
    group: "trustee",
  },
  {
    id: "hibaler",
    name: "Irvin S. Hibaler",
    role: "Trustee",
    pmaClass: "PMA '11",
    image: "/board/hibaler.png",
    highlights: [
      "Chief, International Military Affairs Branch, Strategic and Special Studies Division, OSSSM",
      "MS Environmental Management",
      "Student, PhD in Environmental Diplomacy and Negotiations",
      "Military Assistant, Anti-Terrorism Council",
      "Program Management Center",
      "Philippine Institute of Environmental Planners",
    ],
    group: "trustee",
  },
  {
    id: "valencia",
    name: "Caesar Bernard N. Valencia",
    role: "Trustee, Ex Officio (PMA Superintendent)",
    pmaClass: "PMA '90",
    image: "/board/valencia.jpg",
    highlights: [
      "PMA Superintendent",
      "Master in Management, University of New South Wales, Canberra, Australia",
      "Vice Commander, Philippine Navy (2022)",
      "Chief of Naval Staff (2021)",
      "Commander, Naval Forces Northern Luzon (2019)",
      "Director, Naval Intelligence Training Institute",
      "Dean of Academics, Naval Officer School Center",
    ],
    group: "trustee",
  },
];

export const officers = boardMembers.filter((m) => m.group === "officer");
export const committeeMembers = boardMembers.filter((m) => m.group === "committee");
export const trustees = boardMembers.filter((m) => m.group === "trustee");
